commands:
  aomultiverse:
    name: 'aomultiverse'
    description: 'Handle worlds with AOMultiverse'
    aliases:
      - mv
      - aomv
      - multiverse
    usage: 'aomultiverse <action> <world-name> [generator-type]'
    argumentUsages:
      1$: 'lut["prefix"] & "&7/" & alias & " &c<action> &7<world-name>"'
      2$: 'lut["prefix"] & "&7/" & alias & " &7<action> &c<world-name>"'
      3$: 'lut["prefix"] & "&7/" & alias & " &7<action> &7<world-name> &c<generator-type>"'
    errorMessages:
      malformedEnum$: |
        lut["prefix"] & "&7The value &c" & value & " &7is not one of (" &
        iter_cat(constant_names, (constant_name) => "&c" & constant_name, "&7, ", "&cNo values available") &
        "&7)"
      internalError$: 'lut["prefix"] & "&4An internal error occurred"'
  spawn:
    name: 'spawn'
    description: 'Teleport yourself to the spawn'
    aliases:
      - aospawn
      - aos
    usage: 'spawn'
    argumentUsages:
      1$: 'lut["prefix"] & "&7/" & alias & "&7"'
    errorMessages:
      internalError$: 'lut["prefix"] & "&4An internal error occurred"'
      
permissions:
  missingMessage$: 'lut["prefix"] & "You\sre lacking the permission: " & permission'
  nodes:
    aomultiverse:
      command: aomultiverse.command
      create-world: aomultiverse.create-world
      edit-world: aomultiverse.edit-world
      delete-world: aomultiverse.delete-world
      teleport: aomultiverse.teleport
      spawn: aomultiverse.spawn
      set-spawn: aomultiverse.setspawn
      load: aomultiverse.load
      
lut:
  prefix: '&8[&5AOMultiverse&8] &7'