# This file contains the configuration settings for the WooOneblock plugin.
# Please make sure to update the following values according to your requirements.

# The name of the plugin.
name: AOMultiverse

# The version of the plugin.
version: '1.0'

# The main class of the plugin.
main: de.alphaomegait.aomultiverse.AOMultiverse

# The API version required by the plugin.
api-version: '1.20'

# The author of the plugin.
author: AlphaOmega-IT

# The database of the plugin.
database: true

# The website of the creators.
website: https://alphaomega-it.de

# The description of the plugin.
description: The plugin provides the functionality of the Multiverse system.